### ISSUE TITLE
Node 16 Deprecation Warning in Workflow Runs

### ISSUE THREAD

**Issue by dzervoudakes** [the-wright-jamie/Update-PR-Info-Action#32]
Looks like we're seeing a Node deprecation warning using this action.

<img width="1535" alt="Screenshot 2024-01-25 at 4 48 07 PM" src="https://github.com/the-wright-jamie/Update-PR-Info-Action/assets/6432641/4af6f55c-8b8f-43a0-9cd4-3de799185d3e">

I think the fix should be a simple update on this line from `node16` to `node20` -- https://github.com/the-wright-jamie/Update-PR-Info-Action/blob/master/action.yml#L5

Happy to open a PR if you're open to contributions.

**Comment by the-wright-jamie** [comment]
Thanks for the heads up! Yeah, currently bogged with a lot of work right now so if you open a PR I'll merge it for you, cheers!

**Comment by dzervoudakes** [comment]
@the-wright-jamie By chance, could you provide me with write access to the repository?  I'm receiving the following error when I attempt to push a new branch:
```
remote: Permission to the-wright-jamie/Update-PR-Info-Action.git denied to dzervoudakes.
fatal: unable to access 'https://github.com/the-wright-jamie/Update-PR-Info-Action.git/': The requested URL returned error: 403
```

Thanks in advance 🍻

**Comment by the-wright-jamie** [comment]
Hey!

Thought I had submitted this comment but apparently not - thanks GitHub Mobile App!

Are you new to open source contributing? If so, welcome! Typically we we don't give people write access for quick fixes like this. Also, I work in security, so please forgive me for practicing caution.

To contribute to an OSS project on GitHub you don't have write access do, you should create a fork and do it that way, push the change to your repo and then open a pull request here (actually, if you start the pull request sequence on your repo, it'll automatically target it for here). 

If you need more detailed instructions I'll try and help you out. I appreciate your assistance, but I have to follow standard procedures - hope you understand!

**Comment by dzervoudakes** [comment]
Pardon my naivety, and also very astute of you -- I have contributed to "open source" projects, though usually within an organization I'm already apart of :)

As such, I appreciate your patience and guidance.  I've created a fork and implemented the change there; PR here -- https://github.com/the-wright-jamie/Update-PR-Info-Action/pull/33

**Comment by the-wright-jamie** [comment]
Awesome stuff, thank you very much! I was worried my presumptuous nature might have scared you off - I try to be helpful but worry that people end up thinking I'm a snob 😛. Reality is I'll take all the help I can get, and I love open source because we all get to learn and contribute together! Anyway, will take a look now I'm sure it'll be grand

**Comment by the-wright-jamie** [comment]
Meged the PR, thanks for your contribution!

Apologies it took so long, I've changed a few things in the configuration that will mean that if you spot this again, and come back to fix it, I should be able to merge it for you when I actually say I'm going to merge it.

Thank you for using this repo - happy coding!

**Comment by dzervoudakes** [comment]
> Meged the PR, thanks for your contribution!
> 
> Apologies it took so long, I've changed a few things in the configuration that will mean that if you spot this again, and come back to fix it, I should be able to merge it for you when I actually say I'm going to merge it.
> 
> Thank you for using this repo - happy coding!

Happy to contribute; thank you for helping to shepherd this along 😄 🍻
