### ISSUE TITLE
Behaviour when regex does not match

### ISSUE THREAD

**Issue by rndev15** [the-wright-jamie/Update-PR-Info-Action#35]
Good day @the-wright-jamie, thank you for your fork.

Is there any opportunity to do nothing when branch does not matches regex? I added this action to our action flow and from time to time we have branches like `hotfix-whatever` that does not matches provided regex. And, as we can see in description, action fails as expected. Any workaround for that?

Thanks!

**Comment by the-wright-jamie** [comment]
Heya!

Yeah, there probably is something that can be done about that. It's been a while since I've worked on this, so I'm going to have to re-read what this actually does under the hood. I'll see what I can do for you.

**Comment by the-wright-jamie** [comment]
Added a new option to error-on-fail - defaults to `true`. 

Make sure your uses line looks like this:
```
- uses: the-wright-jamie/update-pr-info-action@master
```
API is unlikely to change too much, so using master should be safe.
